apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: mce
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
<<<<<<< HEAD
          image: 343938549827.dkr.ecr.us-east-1.amazonaws.com/cart-repo-mce-2
=======
          image: 150429528430.dkr.ecr.us-east-1.amazonaws.com/cart-repo-mce-2:latest
>>>>>>> 604119d35203258af682b42100d5a4008a956b65
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "150m"
              memory: "200Mi"
            limits:
              cpu: "700m"
              memory: "700Mi"
          env:
            - name: SERVICE_NAME
              value: "cart"
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AWS_REGION
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AWS_REGION
            - name: DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DYNAMODB_TABLE_CART
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: KAFKA_BOOTSTRAP




