apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mce
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 343938549827.dkr.ecr.us-east-1.amazonaws.com/frontend-repo-mce:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SERVICE_NAME
              value: "frontend"
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: SEARCH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SEARCH_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CART_SERVICE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AWS_REGION
            - name: AWS_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AWS_ACCOUNT_ID

