apiVersion: v1
kind: Secret
metadata:
  name: mce-secrets
  namespace: mce
type: Opaque
stringData:
  POSTGRES_USER: "dbuser"
<<<<<<< HEAD
  POSTGRES_PASSWORD: "Milap@1234"
=======
  POSTGRES_PASSWORD: "kalp#06052003"
>>>>>>> 604119d35203258af682b42100d5a4008a956b65
  POSTGRES_DB: "ecommerce"
  OPENSEARCH_USERNAME: "<OS_USER>"
  OPENSEARCH_PASSWORD: "<OS_PASS>"
  KAFKA_SASL_USERNAME: "<OPTIONAL_KAFKA_USER>"
  KAFKA_SASL_PASSWORD: "<OPTIONAL_KAFKA_PASS>"
