apiVersion: v1
kind: Secret
metadata:
  name: mce-secrets
  namespace: mce
type: Opaque
stringData:
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "Milap@1234"
  POSTGRES_DB: "ecommerce"
  OPENSEARCH_USERNAME: "<OS_USER>"
  OPENSEARCH_PASSWORD: "<OS_PASS>"
  KAFKA_SASL_USERNAME: "<OPTIONAL_KAFKA_USER>"
  KAFKA_SASL_PASSWORD: "<OPTIONAL_KAFKA_PASS>"
