apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search
  namespace: observability
  labels:
    team: mce
spec:
  selector:
    matchLabels:
      app: search
  namespaceSelector:
    matchNames:
      - mce
  endpoints:
    - port: http
      path: /metrics
      interval: 10s