apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: mce
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product

          image: 343938549827.dkr.ecr.us-east-1.amazonaws.com/product-repo-mce-2:latest

          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: PGSSLMODE
              value: "require"
            - name: SERVICE_NAME
              value: "product"
            - name: SERVICE_NAME
              value: "product"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: RDS_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: RDS_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mce-secrets
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mce-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "ecommerce"
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: KAFKA_BOOTSTRAP

