apiVersion: v1
kind: Service
metadata:
  name: analytics-consumer
  namespace: mce
spec:
  selector:
    app: analytics-consumer
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
