apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-producer
  namespace: mce
  labels:
    app: events-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-producer
  template:
    metadata:
      labels:
        app: events-producer
    spec:
      containers:
        - name: events-producer
          image: 343938549827.dkr.ecr.us-east-1.amazonaws.com/events-producer-repo-mce-2
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: SERVICE_NAME
              value: "events-producer"
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: KAFKA_BOOTSTRAP
