apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-producer
  namespace: mce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-producer
  template:
    metadata:
      labels:
        app: events-producer
    spec:
      containers:
        - name: events-producer
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/events-producer-repo-mce:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "b-1.msk.<REGION>.amazonaws.com:9092"
