apiVersion: v1
kind: Service
metadata:
  name: events-producer
  namespace: mce
  labels:
    app: events-producer
spec:
  type: ClusterIP
  selector:
    app: events-producer
  ports:
    - name: http
      port: 80
      targetPort: 8000

