apiVersion: v1
kind: Service
metadata:
  name: events-producer
  namespace: mce
spec:
  selector:
    app: events-producer
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000


